import { ModelConfig } from '../types';

export const AVAILABLE_MODELS: Record<'fast' | 'photo', ModelConfig> = {
  fast: {
    id: 'fast',
    name: 'Real-ESRGAN Fast',
    badge: 'Ultra-Light INT8 (644 KB)',
    architecture: 'RealESR-AnimeVideoV3 (INT8)',
    scale: 4,
    version: 'realesrgan-v3-int8',
    downloadUrl: 'https://huggingface.co/universonic/RealESRGAN/resolve/main/realesr-animevideov3_fp32.onnx',
    fileName: 'model.onnx',
    recommendedTileSizes: [128, 256, 512],
    defaultTileSize: 256,
    overlap: 16,
    estimatedMemoryMB: 120,
    description: 'Ultra-compressed INT8 model (644 KB). Fast ~0.5s tile processing on both CPU and WebGPU with minimal memory footprint.',
    bestFor: [
      'Everyday photos & snapshots',
      'Social media compressed JPEGs',
      'Screenshots and UI graphics',
      'Anime & digital artwork',
      'Low to mid-range GPUs, laptops & mobile',
    ],
  },
  photo: {
    id: 'photo',
    name: 'Real-ESRGAN Photo',
    badge: 'High Fidelity INT8 (16.7 MB)',
    architecture: 'RealESRGAN-x4-INT8',
    scale: 4,
    version: 'realesrgan-photo-int8',
    downloadUrl: 'https://huggingface.co/Wszelkiebro/reliquary-realesrgan-x4-int8/resolve/main/realesrgan_x4_int8.onnx',
    fileName: 'model.onnx',
    recommendedTileSizes: [128, 256],
    defaultTileSize: 256,
    overlap: 16,
    estimatedMemoryMB: 450,
    description: 'Compressed 16.7 MB neural network delivering realistic textures and high fidelity with 3× faster inference than uncompressed models.',
    bestFor: [
      'Real DSLR & mirrorless photography',
      'Portraits, skin and hair details',
      'Nature, foliage and landscape textures',
      'Vintage & heritage photo restoration',
      'Modern dedicated GPUs & multi-core CPUs',
    ],
  },
};
